# Generated by Django 6.0.2 on 2026-02-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_dec_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsprediction',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
